"""empty message

Revision ID: 1d38678e9a6d
Revises: c2b758943da7
Create Date: 2022-02-21 19:10:34.623377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d38678e9a6d'
down_revision = 'c2b758943da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boars', sa.Column('line_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'boars', 'lines', ['line_id'], ['id'])
    op.drop_column('boars', 'line')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boars', sa.Column('line', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'boars', type_='foreignkey')
    op.drop_column('boars', 'line_id')
    # ### end Alembic commands ###
