"""initial migration

Revision ID: 49767561bf1a
Revises: 
Create Date: 2022-02-03 21:43:04.558393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49767561bf1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boars', sa.Column('culling_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boars', 'culling_on')
    # ### end Alembic commands ###
