"""empty message

Revision ID: 67b37213b916
Revises: 49767561bf1a
Create Date: 2022-02-06 09:21:04.288095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b37213b916'
down_revision = '49767561bf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boars', sa.Column('farm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'boars', 'farms', ['farm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boars', type_='foreignkey')
    op.drop_column('boars', 'farm_id')
    # ### end Alembic commands ###
