"""empty message

Revision ID: edefcec14e23
Revises: d4e89e230efc
Create Date: 2022-02-23 06:05:04.264219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edefcec14e23'
down_revision = 'd4e89e230efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('statuses', sa.Column('reason', sa.String(length=50), nullable=True))
    op.add_column('statuses', sa.Column('start_on', sa.Date(), nullable=True))
    op.add_column('statuses', sa.Column('boar_id', sa.Integer(), nullable=True))
    op.drop_constraint('statuses_abbreviation_key', 'statuses', type_='unique')
    op.drop_constraint('statuses_code_key', 'statuses', type_='unique')
    op.drop_constraint('statuses_line_key', 'statuses', type_='unique')
    op.drop_constraint('statuses_name_key', 'statuses', type_='unique')
    op.create_foreign_key(None, 'statuses', 'boars', ['boar_id'], ['id'])
    op.drop_column('statuses', 'abbreviation')
    op.drop_column('statuses', 'name')
    op.drop_column('statuses', 'code')
    op.drop_column('statuses', 'line')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('line', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('statuses', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('statuses', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('statuses', sa.Column('abbreviation', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'statuses', type_='foreignkey')
    op.create_unique_constraint('statuses_name_key', 'statuses', ['name'])
    op.create_unique_constraint('statuses_line_key', 'statuses', ['line'])
    op.create_unique_constraint('statuses_code_key', 'statuses', ['code'])
    op.create_unique_constraint('statuses_abbreviation_key', 'statuses', ['abbreviation'])
    op.drop_column('statuses', 'boar_id')
    op.drop_column('statuses', 'start_on')
    op.drop_column('statuses', 'reason')
    op.drop_column('statuses', 'status')
    # ### end Alembic commands ###
